### ISSUE TITLE
Chapter 6 : ng-annotate and uglify gives me an error

### ISSUE THREAD

**Issue by fkkcloud** [dickeyxxx/mean-sample#22]
when I just run ng-annotate, 
it gives me,
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: app.js: error: couldn't process source due to parse error
Unexpected token (8:8)
    at transform (/Users/user/Desktop/mean_ssn/node_modules/gulp-ng-annotate/index.js:20:11)
    at Transform._transform (/Users/user/Desktop/mean_ssn/node_modules/gulp-ng-annotate/index.js:68:25)
    at Transform._read (/Users/user/Desktop/mean_ssn/node_modules/gulp-ng-annotate/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:184:10)
    at Transform._write (/Users/user/Desktop/mean_ssn/node_modules/gulp-ng-annotate/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:172:12)
    at doWrite (/Users/user/Desktop/mean_ssn/node_modules/gulp-ng-annotate/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:237:10)
    at writeOrBuffer (/Users/user/Desktop/mean_ssn/node_modules/gulp-ng-annotate/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:227:5)
    at Transform.Writable.write (/Users/user/Desktop/mean_ssn/node_modules/gulp-ng-annotate/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:194:11)
    at write (/Users/user/Desktop/mean_ssn/node_modules/gulp-concat/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:623:24)
    at flow (/Users/user/Desktop/mean_ssn/node_modules/gulp-concat/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:632:7)
    at DestroyableTransform.pipeOnReadable (/Users/user/Desktop/mean_ssn/node_modules/gulp-concat/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:664:5)

------------------------------------------------------------------------------------------------------------------------------------

when I just run uglify
it gives me,
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error
    at new JS_Parse_Error (/Users/user/Desktop/mean_ssn/node_modules/gulp-uglify/node_modules/uglify-js/lib/parse.js:196:18)
    at js_error (/Users/user/Desktop/mean_ssn/node_modules/gulp-uglify/node_modules/uglify-js/lib/parse.js:204:11)
    at croak (/Users/user/Desktop/mean_ssn/node_modules/gulp-uglify/node_modules/uglify-js/lib/parse.js:679:41)
    at token_error (/Users/user/Desktop/mean_ssn/node_modules/gulp-uglify/node_modules/uglify-js/lib/parse.js:683:9)
    at expect_token (/Users/user/Desktop/mean_ssn/node_modules/gulp-uglify/node_modules/uglify-js/lib/parse.js:696:9)
    at expect (/Users/user/Desktop/mean_ssn/node_modules/gulp-uglify/node_modules/uglify-js/lib/parse.js:699:36)
    at /Users/user/Desktop/mean_ssn/node_modules/gulp-uglify/node_modules/uglify-js/lib/parse.js:1225:44
    at /Users/user/Desktop/mean_ssn/node_modules/gulp-uglify/node_modules/uglify-js/lib/parse.js:722:24
    at expr_atom (/Users/user/Desktop/mean_ssn/node_modules/gulp-uglify/node_modules/uglify-js/lib/parse.js:1182:35)
    at maybe_unary (/Users/user/Desktop/mean_ssn/node_modules/gulp-uglify/node_modules/uglify-js/lib/parse.js:1358:19)

**Comment by dickeyxxx** [comment]
that means there is a syntax error in your javascript file
